--- # Debugging
-   hosts: '{{ myHosts }}'
    remote_user: centos
    become: yes
    become_method: sudo
    connection: ssh
    gather_facts: '{{ gather }}'
    vars:
        myHosts: centos
        gather: yes
        pkg: telnet
    tasks:
    - shell: cat /etc/ansible/hosts
      register: hosts
    - debug: var=hosts
    - debug: msg="Hosts File is empty"  
      when: hosts.stdout == ""
