--- # Multiple Tasks on Multiple Servers in Single Playbook
- hosts: centos
  remote_user: centos
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes    
  tasks:
  - name: Install lynx on centos Servers
    yum: pkg=lynx state=installed update_cache=true
  - name: Querying for Telnet Install
    yum: pkg=telnet state=present update_cache=true
 
- hosts: webserver
  remote_user: centos
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes    
  tasks:
  - name: Install telnet on Local Server
    yum: pkg=telnet state=installed update_cache=true
  - name: Querying for Httpd Install
    yum: pkg=httpd state=present update_cache=true